### ISSUE TITLE
facing a issue on my simple crud app

### ISSUE THREAD

**Issue by prinsi-t** [prinsi-t/crud-app#1]
when i am trying to click on the 'replace yodas quote'  :

![Screenshot (561)](https://github.com/prinsi-t/crud-app/assets/116324634/51a79ea4-10bc-4f22-83fc-fd92e95e0b17)

its console logging 'null' instead of the result 

![Screenshot (560)](https://github.com/prinsi-t/crud-app/assets/116324634/45541502-1326-45ce-ac52-85c501e3683a)

help me fix this issue

**Comment by Gurnav224** [comment]
![Screenshot from 2024-08-11 14-17-40](https://github.com/user-attachments/assets/73aa0380-f6f3-4308-ba2e-e1c760b26c89)


In order for our system to function properly, we need to include additional options in the findOneAndUpdate MongoDB query:
upsert - true
Upsert is a combination of insert and update. It first checks if a document with the name "yoda" already exists. If it is found, it updates the document. If it is not found, it adds a new document.
returnDocument: "after"
This option returns the document after it has been updated.


**Make sure that when updating Star Wars, use a client-side fetch put request {name:'Yoda'} and make sure that the backend endpoint put request name matches the name being updated in Star Wars .**


![Screenshot from 2024-08-11 13-52-32](https://github.com/user-attachments/assets/e2694af7-f20e-477c-9e6d-fc7b81b67613)

**Comment by prinsi-t** [comment]
@Gurnav224 hey thanks for the help appreciate it!
